services:
  site:
    container_name: application
    build:
      context: ./

    ports:
      - 8080:8080

    environment:
      DB_DRIVER: mysql
      DB_HOST: site-db
      DB_USER: phalcon_site
      DB_PASS: password
      DB_NAME: phalcon_site
      APP_ENV: local

    depends_on:
      - site-db

    volumes:
      - ./docker-compose/nginx/:/etc/nginx/conf.d/
      - ./docker-compose/php/zz-custom.ini:/etc/php/8.3/fpm/conf.d/zz-custom.ini
      - ./site/:/srv/www/
      - site-uploads:/srv/www/storage/uploads

    networks:
      - public
      - private

  site-db:
    image: ubuntu/mysql
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: phalcon_site
      MYSQL_ROOT_PASSWORD: f8dJ#*fd
      MYSQL_PASSWORD: password
      MYSQL_USER: phalcon_site
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - site-database:/var/lib/mysql

    networks:
      - private

networks:
  public:
  private:

volumes:
  site-database:
    driver: local

  site-uploads:
    driver: local