<form action="/contact" method="post">
    <input type="hidden" value="<?= $_SESSION['_csrf'] ?>" name="_csrf">

    <div>
        <label for="name">Name</label>
        <input type="text" name="name" id="name">
    </div>

    <div>
        <label for="email">Email</label>
        <input type="email" name="email" id="email">
    </div>

    <div>
        <label for="comments">Comments</label>
        <textarea name="comments" id="comments" cols="30" rows="10"></textarea>
    </div>

    <button>Submit</button>
</form>